# Boss database for the API
# Data gathered from Fextralife / Fandom wiki
BOSS_DATABASE = {
    "Godrick the Grafted": {
        "name": "Godrick the Grafted",
        "region": "Limgrave",
        "phase": 2,
        "type": "Demigod",
        "race": "Humanoid",
        "specific_location": "Stormveil Castle",
        "mandatory": False,
        "dlc": False,
        "runes": 20000,
        "image_url": "/static/images/Godrick_the_Grafted.jpg"
    },
    "Rennala, Queen of the Full Moon": {
        "name": "Rennala, Queen of the Full Moon",
        "region": "Liurnia of the Lakes",
        "phase": 2,
        "type": "Legend",
        "race": "Humanoid",
        "specific_location": "Raya Lucaria Academy",
        "mandatory": False,
        "dlc": False,
        "runes": 40000,
        "image_url": "/static/images/Rennala_Queen_of_the_Full_Moon.jpg"
    },
    "Starscourge Radahn": {
        "name": "Starscourge Radahn",
        "region": "Caelid",
        "phase": 2,
        "type": "Demigod",
        "race": "Humanoid",
        "specific_location": "Wailing Dunes",
        "mandatory": False,
        "dlc": False,
        "runes": 70000,
        "image_url": "/static/images/Starscourge_Radahn.jpg"
    },
    "Rykard, Lord of Blasphemy": {
        "name": "Rykard, Lord of Blasphemy",
        "region": "Mt. Gelmir",
        "phase": 2,
        "type": "Demigod",
        "race": "Serpent",
        "specific_location": "Volcano Manor",
        "mandatory": False,
        "dlc": False,
        "runes": 130000,
        "image_url": "/static/images/Rykard_Lord_of_Blasphemy.jpg"
    },
    "Morgott, the Omen King": {
        "name": "Morgott, the Omen King",
        "region": "Leyndell, Royal Capital",
        "phase": 2,
        "type": "Demigod",
        "race": "Omen",
        "specific_location": "Elden Throne",
        "mandatory": True,
        "dlc": False,
        "runes": 120000,
        "image_url": "/static/images/Morgott_the_Omen_King.jpg"
    },
    "Fire Giant": {
        "name": "Fire Giant",
        "region": "Mountaintops of the Giants",
        "phase": 2,
        "type": "Legend",
        "race": "Giant",
        "specific_location": "Flame Peak",
        "mandatory": True,
        "dlc": False,
        "runes": 180000,
        "image_url": "/static/images/Fire_Giant.jpg"
    },
    "Maliketh, the Black Blade": {
        "name": "Maliketh, the Black Blade",
        "region": "Crumbling Farum Azula",
        "phase": 2,
        "type": "Legend",
        "race": "Beast",
        "specific_location": "Beside the Great Bridge",
        "mandatory": True,
        "dlc": False,
        "runes": 220000,
        "image_url": "/static/images/Maliketh_the_Black_Blade.jpg"
    },
    "Godfrey, First Elden Lord": {
        "name": "Godfrey, First Elden Lord",
        "region": "Leyndell, Ashen Capital",
        "phase": 2,
        "type": "Legend",
        "race": "Humanoid",
        "specific_location": "Elden Throne",
        "mandatory": True,
        "dlc": False,
        "runes": 280000,
        "image_url": "/static/images/Godfrey_First_Elden_Lord.jpg"
    },
    "Radagon of the Golden Order": {
        "name": "Radagon of the Golden Order",
        "region": "Leyndell, Ashen Capital",
        "phase": 1,
        "type": "Legend",
        "race": "Humanoid",
        "specific_location": "Elden Throne",
        "mandatory": True,
        "dlc": False,
        "runes": 500000,
        "image_url": "/static/images/Radagon_of_the_Golden_Order.jpg"
    },
    "Elden Beast": {
        "name": "Elden Beast",
        "region": "Leyndell, Ashen Capital",
        "phase": 1,
        "type": "Legend",
        "race": "Elden Beast",
        "specific_location": "Elden Throne",
        "mandatory": True,
        "dlc": False,
        "runes": 500000,
        "image_url": "/static/images/Elden_Beast.jpg"
    },
    "Malenia, Blade of Miquella": {
        "name": "Malenia, Blade of Miquella",
        "region": "Consecrated Snowfield",
        "phase": 2,
        "type": "Demigod",
        "race": "Humanoid",
        "specific_location": "Miquella's Haligtree",
        "mandatory": False,
        "dlc": False,
        "runes": 480000,
        "image_url": "/static/images/Malenia_Blade_of_Miquella.jpg"
    },
    "Mohg, Lord of Blood": {
        "name": "Mohg, Lord of Blood",
        "region": "Siofra River",
        "phase": 2,
        "type": "Demigod",
        "race": "Omen",
        "specific_location": "Mohgwyn Palace",
        "mandatory": False,
        "dlc": False,
        "runes": 420000,
        "image_url": "/static/images/Mohg_Lord_of_Blood.jpg"
    },
    "Hoarah Loux, Warrior": {
        "name": "Hoarah Loux, Warrior",
        "region": "Leyndell, Ashen Capital",
        "phase": 2,
        "type": "Legend",
        "race": "Humanoid",
        "specific_location": "Elden Throne",
        "mandatory": True,
        "dlc": False,
        "runes": 280000,
        "image_url": "/static/images/Hoarah_Loux_Warrior.jpg"
    },
    "Margit, the Fell Omen": {
        "name": "Margit, the Fell Omen",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Omen",
        "specific_location": "Stormveil Castle",
        "mandatory": False,
        "dlc": False,
        "runes": 12000,
        "image_url": "/static/images/Margit_the_Fell_Omen.jpg"
    },
    "Grafted Scion": {
        "name": "Grafted Scion",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Construct",
        "specific_location": "Chapel of Anticipation",
        "mandatory": False,
        "dlc": False,
        "runes": 3200,
        "image_url": "/static/images/Grafted_Scion.jpg"
    },
    "Soldier of Godrick": {
        "name": "Soldier of Godrick",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Stranded Graveyard",
        "mandatory": True,
        "dlc": False,
        "runes": 400,
        "image_url": "/static/images/Soldier_of_Godrick.jpg"
    },
    "Leonine Misbegotten": {
        "name": "Leonine Misbegotten",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Misbegotten",
        "specific_location": "Castle Morne",
        "mandatory": False,
        "dlc": False,
        "runes": 3800,
        "image_url": "/static/images/Leonine_Misbegotten.jpg"
    },
    "Tree Sentinel": {
        "name": "Tree Sentinel",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Construct",
        "specific_location": "Limgrave",
        "mandatory": False,
        "dlc": False,
        "runes": 3200,
        "image_url": "/static/images/Tree_Sentinel.jpg"
    },
    "Crucible Knight": {
        "name": "Crucible Knight",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Stormhill Evergaol",
        "mandatory": False,
        "dlc": False,
        "runes": 3200,
        "image_url": "/static/images/Crucible_Knight.jpg"
    },
    "Demi-Human Chiefs": {
        "name": "Demi-Human Chiefs",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Demi-Human",
        "specific_location": "Coastal Cave",
        "mandatory": False,
        "dlc": False,
        "runes": 1000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Pumpkin Head": {
        "name": "Pumpkin Head",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Pumpkin Head's Cave",
        "mandatory": False,
        "dlc": False,
        "runes": 1000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Flying Dragon Agheel": {
        "name": "Flying Dragon Agheel",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Dragon-Burnt Ruins",
        "mandatory": False,
        "dlc": False,
        "runes": 5000,
        "image_url": "/static/images/Flying_Dragon_Agheel.jpg"
    },
    "Tibia Mariner": {
        "name": "Tibia Mariner",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Undead",
        "specific_location": "Summonwater Village",
        "mandatory": False,
        "dlc": False,
        "runes": 3400,
        "image_url": "/static/images/Tibia_Mariner.jpg"
    },
    "Beastman of Farum Azula": {
        "name": "Beastman of Farum Azula",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Beast",
        "specific_location": "Groveside Cave",
        "mandatory": False,
        "dlc": False,
        "runes": 1500,
        "image_url": "/static/images/Beastman_of_Farum_Azula.jpg"
    },
    "Night's Cavalry": {
        "name": "Night's Cavalry",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Undead",
        "specific_location": "Agheel Lake North",
        "mandatory": False,
        "dlc": False,
        "runes": 2400,
        "image_url": "/static/images/Nights_Cavalry.jpg"
    },
    "Bloodhound Knight Darriwil": {
        "name": "Bloodhound Knight Darriwil",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Beast",
        "specific_location": "Forlorn Hound Evergaol",
        "mandatory": False,
        "dlc": False,
        "runes": 1900,
        "image_url": "/static/images/Bloodhound_Knight_Darriwil.jpg"
    },
    "Grave Warden Duelist": {
        "name": "Grave Warden Duelist",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Murkwater Catacombs",
        "mandatory": False,
        "dlc": False,
        "runes": 1000,
        "image_url": "/static/images/Grave_Warden_Duelist.jpg"
    },
    "Stonedigger Troll": {
        "name": "Stonedigger Troll",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Troll",
        "specific_location": "Old Altus Tunnel",
        "mandatory": False,
        "dlc": False,
        "runes": 1500,
        "image_url": "/static/images/Stonedigger_Troll.jpg"
    },
    "Patches": {
        "name": "Patches",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Murkwater Cave",
        "mandatory": False,
        "dlc": False,
        "runes": 1700,
        "image_url": "/static/images/Patches.jpg"
    },
    "Mad Pumpkin Head": {
        "name": "Mad Pumpkin Head",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Waypoint Ruins",
        "mandatory": False,
        "dlc": False,
        "runes": 1100,
        "image_url": "/static/images/Mad_Pumpkin_Head.jpg"
    },
    "Deathbird": {
        "name": "Deathbird",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Bird",
        "specific_location": "Limgrave",
        "mandatory": False,
        "dlc": False,
        "runes": 2900,
        "image_url": "/static/images/Deathbird.jpg"
    },
    "Bell Bearing Hunter": {
        "name": "Bell Bearing Hunter",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Warmaster's Shack",
        "mandatory": False,
        "dlc": False,
        "runes": 3300,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Erdtree Burial Watchdog": {
        "name": "Erdtree Burial Watchdog",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Construct",
        "specific_location": "Stormfoot Catacombs",
        "mandatory": False,
        "dlc": False,
        "runes": 1300,
        "image_url": "/static/images/Erdtree_Burial_Watchdog.jpg"
    },
    "Demi-Human Queen Gilika": {
        "name": "Demi-Human Queen Gilika",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Demi-Human",
        "specific_location": "Lenne's Rise",
        "mandatory": False,
        "dlc": False,
        "runes": 1200,
        "image_url": "/static/images/Demi-Human_Queen_Gilika.jpg"
    },
    "Miranda the Blighted Bloom": {
        "name": "Miranda the Blighted Bloom",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Plant",
        "specific_location": "Tombsward Cave",
        "mandatory": False,
        "dlc": False,
        "runes": 2000,
        "image_url": "/static/images/Miranda_the_Blighted_Bloom.jpg"
    },
    "Scaly Misbegotten": {
        "name": "Scaly Misbegotten",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Misbegotten",
        "specific_location": "Morne Tunnel",
        "mandatory": False,
        "dlc": False,
        "runes": 1000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Bloodhound Knight": {
        "name": "Bloodhound Knight",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Beast",
        "specific_location": "Volcano Manor",
        "mandatory": False,
        "dlc": False,
        "runes": 7800,
        "image_url": "/static/images/Bloodhound_Knight.jpg"
    },
    "Red Wolf of Radagon": {
        "name": "Red Wolf of Radagon",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Beast",
        "specific_location": "Raya Lucaria Academy",
        "mandatory": False,
        "dlc": False,
        "runes": 14000,
        "image_url": "/static/images/Red_Wolf_of_Radagon.jpg"
    },
    "Royal Knight Loretta": {
        "name": "Royal Knight Loretta",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Caria Manor",
        "mandatory": False,
        "dlc": False,
        "runes": 10000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Glintstone Dragon Smarag": {
        "name": "Glintstone Dragon Smarag",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Academy Gate Town",
        "mandatory": False,
        "dlc": False,
        "runes": 18000,
        "image_url": "/static/images/Glintstone_Dragon_Smarag.jpg"
    },
    "Erdtree Avatar": {
        "name": "Erdtree Avatar",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Tree Avatar",
        "specific_location": "Minor Erdtree",
        "mandatory": False,
        "dlc": False,
        "runes": 7000,
        "image_url": "/static/images/Erdtree_Avatar.jpg"
    },
    "Adan, Thief of Fire": {
        "name": "Adan, Thief of Fire",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Malefactor's Evergaol",
        "mandatory": False,
        "dlc": False,
        "runes": 3800,
        "image_url": "/static/images/Adan_Thief_of_Fire.jpg"
    },
    "Magma Wyrm Makar": {
        "name": "Magma Wyrm Makar",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Ruin-Strewn Precipice",
        "mandatory": False,
        "dlc": False,
        "runes": 18000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Crystalian": {
        "name": "Crystalian",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Construct",
        "specific_location": "Academy Crystal Cave",
        "mandatory": False,
        "dlc": False,
        "runes": 1800,
        "image_url": "/static/images/Crystalian.jpg"
    },
    "Bols, Carian Knight": {
        "name": "Bols, Carian Knight",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Troll",
        "specific_location": "Cuckoo's Evergaol",
        "mandatory": False,
        "dlc": False,
        "runes": 4000,
        "image_url": "/static/images/Bols_Carian_Knight.jpg"
    },
    "Glintstone Dragon Adula": {
        "name": "Glintstone Dragon Adula",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Cathedral of Manus Celes",
        "mandatory": False,
        "dlc": False,
        "runes": 100000,
        "image_url": "/static/images/Glintstone_Dragon_Adula.jpg"
    },
    "Spirit-Caller Snail": {
        "name": "Spirit-Caller Snail",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Snail",
        "specific_location": "Road's End Catacombs",
        "mandatory": False,
        "dlc": False,
        "runes": 1900,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Nox Swordstress & Nox Priest": {
        "name": "Nox Swordstress & Nox Priest",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Eternal City of Nokstella",
        "mandatory": False,
        "dlc": False,
        "runes": 7800,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Cemetery Shade": {
        "name": "Cemetery Shade",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Undead",
        "specific_location": "Black Knife Catacombs",
        "mandatory": False,
        "dlc": False,
        "runes": 5400,
        "image_url": "/static/images/Cemetery_Shade.jpg"
    },
    "Demi-Human Queen Maggie": {
        "name": "Demi-Human Queen Maggie",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Demi-Human",
        "specific_location": "Hermit Village",
        "mandatory": False,
        "dlc": False,
        "runes": 7500,
        "image_url": "/static/images/Demi-Human_Queen_Maggie.jpg"
    },
    "Tibia Mariner (Liurnia)": {
        "name": "Tibia Mariner (Liurnia)",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Undead",
        "specific_location": "Liurnia of the Lakes",
        "mandatory": False,
        "dlc": False,
        "runes": 4900,
        "image_url": "/static/images/Tibia_Mariner.jpg"
    },
    "Omenkiller": {
        "name": "Omenkiller",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Village of the Albinaurics",
        "mandatory": False,
        "dlc": False,
        "runes": 10000,
        "image_url": "/static/images/Omenkiller.jpg"
    },
    "Bloodhound Knight (Liurnia)": {
        "name": "Bloodhound Knight (Liurnia)",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Beast",
        "specific_location": "Lakeside Crystal Cave",
        "mandatory": False,
        "dlc": False,
        "runes": 4200,
        "image_url": "/static/images/Bloodhound_Knight.jpg"
    },
    "Starscourge Radahn (Festival)": {
        "name": "Starscourge Radahn (Festival)",
        "region": "Caelid",
        "phase": 2,
        "type": "Demigod",
        "race": "Humanoid",
        "specific_location": "Wailing Dunes",
        "mandatory": False,
        "dlc": False,
        "runes": 70000,
        "image_url": "/static/images/Starscourge_Radahn.jpg"
    },
    "Commander O'Neil": {
        "name": "Commander O'Neil",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Swamp of Aeonia",
        "mandatory": False,
        "dlc": False,
        "runes": 12000,
        "image_url": "/static/images/Commander_ONeil.jpg"
    },
    "Putrid Avatar": {
        "name": "Putrid Avatar",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Tree Avatar",
        "specific_location": "Caelid",
        "mandatory": False,
        "dlc": False,
        "runes": 24000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Battlemage Hugues": {
        "name": "Battlemage Hugues",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Sellia Evergaol",
        "mandatory": False,
        "dlc": False,
        "runes": 8400,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Bell Bearing Hunter (Caelid)": {
        "name": "Bell Bearing Hunter (Caelid)",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Isolated Merchant's Shack",
        "mandatory": False,
        "dlc": False,
        "runes": 39000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Cleanrot Knight": {
        "name": "Cleanrot Knight",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Stillwater Cave",
        "mandatory": False,
        "dlc": False,
        "runes": 7700,
        "image_url": "/static/images/Cleanrot_Knight.jpg"
    },
    "Black Blade Kindred": {
        "name": "Black Blade Kindred",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Gargoyle",
        "specific_location": "Bestial Sanctum",
        "mandatory": False,
        "dlc": False,
        "runes": 80000,
        "image_url": "/static/images/Black_Blade_Kindred.jpg"
    },
    "Flying Dragon Greyll": {
        "name": "Flying Dragon Greyll",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Dragonbarrow",
        "mandatory": False,
        "dlc": False,
        "runes": 80000,
        "image_url": "/static/images/Flying_Dragon_Greyll.jpg"
    },
    "Nox Swordstress": {
        "name": "Nox Swordstress",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Sellia, Town of Sorcery",
        "mandatory": False,
        "dlc": False,
        "runes": 4200,
        "image_url": "/static/images/Nox_Swordstress.jpg"
    },
    "Death Rite Bird (Caelid)": {
        "name": "Death Rite Bird (Caelid)",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Bird",
        "specific_location": "Caelid",
        "mandatory": False,
        "dlc": False,
        "runes": 13000,
        "image_url": "/static/images/Death_Rite_Bird_Caelid.jpg"
    },
    "Putrid Crystalian Trio": {
        "name": "Putrid Crystalian Trio",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Construct",
        "specific_location": "Sellia Crystal Tunnel",
        "mandatory": False,
        "dlc": False,
        "runes": 20000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Putrid Tree Spirit": {
        "name": "Putrid Tree Spirit",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Tree Avatar",
        "specific_location": "War-Dead Catacombs",
        "mandatory": False,
        "dlc": False,
        "runes": 24000,
        "image_url": "/static/images/Putrid_Tree_Spirit.jpg"
    },
    "Godskin Apostle (Dragonbarrow)": {
        "name": "Godskin Apostle (Dragonbarrow)",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Godskin",
        "specific_location": "Dragonbarrow",
        "mandatory": False,
        "dlc": False,
        "runes": 46000,
        "image_url": "/static/images/Godskin_Apostle_Dragonbarrow.jpg"
    },
    "Godfrey, First Elden Lord (Golden Shade)": {
        "name": "Godfrey, First Elden Lord (Golden Shade)",
        "region": "Leyndell, Royal Capital",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Leyndell, Royal Capital",
        "mandatory": True,
        "dlc": False,
        "runes": 80000,
        "image_url": "/static/images/Godfrey_First_Elden_Lord.jpg"
    },
    "Elemer of the Briar": {
        "name": "Elemer of the Briar",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "The Shaded Castle",
        "mandatory": False,
        "dlc": False,
        "runes": 26000,
        "image_url": "/static/images/Elemer_of_the_Briar.jpg"
    },
    "Fallingstar Beast (Altus)": {
        "name": "Fallingstar Beast (Altus)",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Aberration",
        "specific_location": "Altus Plateau",
        "mandatory": False,
        "dlc": False,
        "runes": 14000,
        "image_url": "/static/images/Fallingstar_Beast_Altus.jpg"
    },
    "Godskin Apostle (Altus)": {
        "name": "Godskin Apostle (Altus)",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Godskin",
        "specific_location": "Dominula, Windmill Village",
        "mandatory": False,
        "dlc": False,
        "runes": 14000,
        "image_url": "/static/images/Godskin_Apostle_Dragonbarrow.jpg"
    },
    "Ancient Dragon Lansseax": {
        "name": "Ancient Dragon Lansseax",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Altus Plateau",
        "mandatory": False,
        "dlc": False,
        "runes": 100000,
        "image_url": "/static/images/Ancient_Dragon_Lansseax.jpg"
    },
    "Draconic Tree Sentinel": {
        "name": "Draconic Tree Sentinel",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Construct",
        "specific_location": "Capital Outskirts",
        "mandatory": False,
        "dlc": False,
        "runes": 50000,
        "image_url": "/static/images/Draconic_Tree_Sentinel.jpg"
    },
    "Omenkiller & Miranda the Blighted Bloom": {
        "name": "Omenkiller & Miranda the Blighted Bloom",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Perfumer's Grotto",
        "mandatory": False,
        "dlc": False,
        "runes": 16000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Crucible Knight Ordovis": {
        "name": "Crucible Knight Ordovis",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Auriza Hero's Grave",
        "mandatory": False,
        "dlc": False,
        "runes": 46000,
        "image_url": "/static/images/Crucible_Knight_Ordovis.jpg"
    },
    "Ancient Hero of Zamor": {
        "name": "Ancient Hero of Zamor",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Sainted Hero's Grave",
        "mandatory": False,
        "dlc": False,
        "runes": 30000,
        "image_url": "/static/images/Ancient_Hero_of_Zamor.jpg"
    },
    "Fell Twins": {
        "name": "Fell Twins",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Leyndell, Royal Capital",
        "mandatory": False,
        "dlc": False,
        "runes": 36000,
        "image_url": "/static/images/Fell_Twins.jpg"
    },
    "Onyx Lord": {
        "name": "Onyx Lord",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Royal Grave Evergaol",
        "mandatory": False,
        "dlc": False,
        "runes": 12000,
        "image_url": "/static/images/Onyx_Lord.jpg"
    },
    "Sanguine Noble": {
        "name": "Sanguine Noble",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Writheblood Ruins",
        "mandatory": False,
        "dlc": False,
        "runes": 9200,
        "image_url": "/static/images/Sanguine_Noble.jpg"
    },
    "Wormface": {
        "name": "Wormface",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Wormface",
        "specific_location": "Altus Plateau",
        "mandatory": False,
        "dlc": False,
        "runes": 12000,
        "image_url": "/static/images/Wormface.jpg"
    },
    "Perfumer Tricia": {
        "name": "Perfumer Tricia",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Unsightly Catacombs",
        "mandatory": False,
        "dlc": False,
        "runes": 20000,
        "image_url": "/static/images/Perfumer_Tricia.jpg"
    },
    "Necromancer Garris": {
        "name": "Necromancer Garris",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Hidden Path to the Haligtree",
        "mandatory": False,
        "dlc": False,
        "runes": 40000,
        "image_url": "/static/images/Necromancer_Garris.jpg"
    },
    "Black Knife Assassin (Altus)": {
        "name": "Black Knife Assassin (Altus)",
        "region": "Altus Plateau",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Sage's Cave",
        "mandatory": False,
        "dlc": False,
        "runes": 11000,
        "image_url": "/static/images/Black_Knife_Assassin_Altus.jpg"
    },
    "Godefroy the Grafted": {
        "name": "Godefroy the Grafted",
        "region": "Altus Plateau",
        "phase": 2,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Altus Plateau",
        "mandatory": False,
        "dlc": False,
        "runes": 75000,
        "image_url": "/static/images/Godefroy_the_Grafted.jpg"
    },
    "Godskin Noble": {
        "name": "Godskin Noble",
        "region": "Mt. Gelmir",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Godskin",
        "specific_location": "Volcano Manor",
        "mandatory": False,
        "dlc": False,
        "runes": 15000,
        "image_url": "/static/images/Godskin_Noble.jpg"
    },
    "Full-Grown Fallingstar Beast": {
        "name": "Full-Grown Fallingstar Beast",
        "region": "Mt. Gelmir",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Aberration",
        "specific_location": "Mt. Gelmir",
        "mandatory": False,
        "dlc": False,
        "runes": 20000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Abductor Virgins": {
        "name": "Abductor Virgins",
        "region": "Mt. Gelmir",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Construct",
        "specific_location": "Volcano Manor",
        "mandatory": False,
        "dlc": False,
        "runes": 15000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Magma Wyrm": {
        "name": "Magma Wyrm",
        "region": "Mt. Gelmir",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Fort Laiedd",
        "mandatory": False,
        "dlc": False,
        "runes": 18000,
        "image_url": "/static/images/Magma_Wyrm.jpg"
    },
    "Red Wolf of the Champion": {
        "name": "Red Wolf of the Champion",
        "region": "Mt. Gelmir",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Beast",
        "specific_location": "Gelmir Hero's Grave",
        "mandatory": False,
        "dlc": False,
        "runes": 28000,
        "image_url": "/static/images/Red_Wolf_of_the_Champion.jpg"
    },
    "Ulcerated Tree Spirit (Gelmir)": {
        "name": "Ulcerated Tree Spirit (Gelmir)",
        "region": "Mt. Gelmir",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Tree Avatar",
        "specific_location": "Mt. Gelmir",
        "mandatory": False,
        "dlc": False,
        "runes": 20000,
        "image_url": "/static/images/Ulcerated_Tree_Spirit_Gelmir.jpg"
    },
    "Demi-Human Queen Margot": {
        "name": "Demi-Human Queen Margot",
        "region": "Mt. Gelmir",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Demi-Human",
        "specific_location": "Mt. Gelmir",
        "mandatory": False,
        "dlc": False,
        "runes": 16000,
        "image_url": "/static/images/Demi-Human_Queen_Margot.jpg"
    },
    "Kindred of Rot": {
        "name": "Kindred of Rot",
        "region": "Mt. Gelmir",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Bug",
        "specific_location": "Seethewater Cave",
        "mandatory": False,
        "dlc": False,
        "runes": 22000,
        "image_url": "/static/images/Kindred_of_Rot.jpg"
    },
    "Mohg, the Omen": {
        "name": "Mohg, the Omen",
        "region": "Leyndell, Royal Capital",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Omen",
        "specific_location": "Subterranean Shunning-Grounds",
        "mandatory": False,
        "dlc": False,
        "runes": 100000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Esgar, Priest of Blood": {
        "name": "Esgar, Priest of Blood",
        "region": "Leyndell, Royal Capital",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Subterranean Shunning-Grounds",
        "mandatory": False,
        "dlc": False,
        "runes": 30000,
        "image_url": "/static/images/Esgar_Priest_of_Blood.jpg"
    },
    "Sir Gideon Ofnir, the All-Knowing": {
        "name": "Sir Gideon Ofnir, the All-Knowing",
        "region": "Leyndell, Ashen Capital",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Leyndell, Ashen Capital",
        "mandatory": True,
        "dlc": False,
        "runes": 170000,
        "image_url": "/static/images/Sir_Gideon_Ofnir_the_All-Knowing.jpg"
    },
    "Ancestor Spirit": {
        "name": "Ancestor Spirit",
        "region": "Siofra River",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Beast",
        "specific_location": "Siofra River",
        "mandatory": False,
        "dlc": False,
        "runes": 13000,
        "image_url": "/static/images/Ancestor_Spirit.jpg"
    },
    "Dragonkin Soldier": {
        "name": "Dragonkin Soldier",
        "region": "Siofra River",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Siofra River",
        "mandatory": False,
        "dlc": False,
        "runes": 10000,
        "image_url": "/static/images/Dragonkin_Soldier.jpg"
    },
    "Mimic Tear": {
        "name": "Mimic Tear",
        "region": "Siofra River",
        "phase": 2,
        "type": "Greater Enemy",
        "race": "Mimic",
        "specific_location": "Nokron, Eternal City",
        "mandatory": False,
        "dlc": False,
        "runes": 20000,
        "image_url": "/static/images/Mimic_Tear.jpg"
    },
    "Regal Ancestor Spirit": {
        "name": "Regal Ancestor Spirit",
        "region": "Siofra River",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Beast",
        "specific_location": "Nokron, Eternal City",
        "mandatory": False,
        "dlc": False,
        "runes": 24000,
        "image_url": "/static/images/Regal_Ancestor_Spirit.jpg"
    },
    "Valiant Gargoyle": {
        "name": "Valiant Gargoyle",
        "region": "Siofra River",
        "phase": 2,
        "type": "Greater Enemy",
        "race": "Gargoyle",
        "specific_location": "Nokron, Eternal City",
        "mandatory": False,
        "dlc": False,
        "runes": 34000,
        "image_url": "/static/images/Valiant_Gargoyle.jpg"
    },
    "Astel, Naturalborn of the Void": {
        "name": "Astel, Naturalborn of the Void",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Aberration",
        "specific_location": "Lake of Rot",
        "mandatory": False,
        "dlc": False,
        "runes": 80000,
        "image_url": "/static/images/Astel_Naturalborn_of_the_Void.jpg"
    },
    "Dragonkin Soldier of Nokstella": {
        "name": "Dragonkin Soldier of Nokstella",
        "region": "Liurnia of the Lakes",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Ainsel River",
        "mandatory": False,
        "dlc": False,
        "runes": 45000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Lichdragon Fortissax": {
        "name": "Lichdragon Fortissax",
        "region": "Siofra River",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Deeproot Depths",
        "mandatory": False,
        "dlc": False,
        "runes": 90000,
        "image_url": "/static/images/Lichdragon_Fortissax.jpg"
    },
    "Crucible Knight Siluria": {
        "name": "Crucible Knight Siluria",
        "region": "Siofra River",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Deeproot Depths",
        "mandatory": False,
        "dlc": False,
        "runes": 30000,
        "image_url": "/static/images/Crucible_Knight_Siluria.jpg"
    },
    "Fia's Champions": {
        "name": "Fia's Champions",
        "region": "Siofra River",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Deeproot Depths",
        "mandatory": False,
        "dlc": False,
        "runes": 49500,
        "image_url": "/static/images/Fias_Champions.jpg"
    },
    "Borealis the Freezing Fog": {
        "name": "Borealis the Freezing Fog",
        "region": "Mountaintops of the Giants",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Mountaintops of the Giants",
        "mandatory": False,
        "dlc": False,
        "runes": 100000,
        "image_url": "/static/images/Borealis_the_Freezing_Fog.jpg"
    },
    "Commander Niall": {
        "name": "Commander Niall",
        "region": "Mountaintops of the Giants",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Castle Sol",
        "mandatory": False,
        "dlc": False,
        "runes": 88000,
        "image_url": "/static/images/Commander_Niall.jpg"
    },
    "Death Rite Bird": {
        "name": "Death Rite Bird",
        "region": "Mountaintops of the Giants",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Bird",
        "specific_location": "Mountaintops of the Giants",
        "mandatory": False,
        "dlc": False,
        "runes": 100000,
        "image_url": "/static/images/Death_Rite_Bird_Caelid.jpg"
    },
    "Vyke, Knight of the Roundtable": {
        "name": "Vyke, Knight of the Roundtable",
        "region": "Mountaintops of the Giants",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Lord Contender's Evergaol",
        "mandatory": False,
        "dlc": False,
        "runes": 102000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Ulcerated Tree Spirit (Mountaintops)": {
        "name": "Ulcerated Tree Spirit (Mountaintops)",
        "region": "Mountaintops of the Giants",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Tree Avatar",
        "specific_location": "Giants' Mountaintop Catacombs",
        "mandatory": False,
        "dlc": False,
        "runes": 35000,
        "image_url": "/static/images/Ulcerated_Tree_Spirit_Gelmir.jpg"
    },
    "Ancient Hero of Zamor (Mountaintops)": {
        "name": "Ancient Hero of Zamor (Mountaintops)",
        "region": "Mountaintops of the Giants",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Zamor Ruins",
        "mandatory": False,
        "dlc": False,
        "runes": 30000,
        "image_url": "/static/images/Ancient_Hero_of_Zamor.jpg"
    },
    "Great Wyrm Theodorix": {
        "name": "Great Wyrm Theodorix",
        "region": "Consecrated Snowfield",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Consecrated Snowfield",
        "mandatory": False,
        "dlc": False,
        "runes": 180000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Astel, Stars of Darkness": {
        "name": "Astel, Stars of Darkness",
        "region": "Consecrated Snowfield",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Aberration",
        "specific_location": "Yelough Anix Tunnel",
        "mandatory": False,
        "dlc": False,
        "runes": 120000,
        "image_url": "/static/images/Astel_Stars_of_Darkness.jpg"
    },
    "Misbegotten Crusader": {
        "name": "Misbegotten Crusader",
        "region": "Consecrated Snowfield",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Misbegotten",
        "specific_location": "Cave of the Forlorn",
        "mandatory": False,
        "dlc": False,
        "runes": 40000,
        "image_url": "/static/images/Misbegotten_Crusader.jpg"
    },
    "Loretta, Knight of the Haligtree": {
        "name": "Loretta, Knight of the Haligtree",
        "region": "Consecrated Snowfield",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Miquella's Haligtree",
        "mandatory": False,
        "dlc": False,
        "runes": 200000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Putrid Grave Warden Duelist": {
        "name": "Putrid Grave Warden Duelist",
        "region": "Consecrated Snowfield",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Consecrated Snowfield Catacombs",
        "mandatory": False,
        "dlc": False,
        "runes": 24000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Night's Cavalry (Duo)": {
        "name": "Night's Cavalry (Duo)",
        "region": "Consecrated Snowfield",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Undead",
        "specific_location": "Consecrated Snowfield",
        "mandatory": False,
        "dlc": False,
        "runes": 34000,
        "image_url": "/static/images/Nights_Cavalry.jpg"
    },
    "Putrid Avatar (Snowfield)": {
        "name": "Putrid Avatar (Snowfield)",
        "region": "Consecrated Snowfield",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Tree Avatar",
        "specific_location": "Consecrated Snowfield",
        "mandatory": False,
        "dlc": False,
        "runes": 60000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Dragonlord Placidusax": {
        "name": "Dragonlord Placidusax",
        "region": "Crumbling Farum Azula",
        "phase": 2,
        "type": "Legend",
        "race": "Dragon",
        "specific_location": "Crumbling Farum Azula",
        "mandatory": False,
        "dlc": False,
        "runes": 280000,
        "image_url": "/static/images/Dragonlord_Placidusax.jpg"
    },
    "Godskin Duo": {
        "name": "Godskin Duo",
        "region": "Crumbling Farum Azula",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Godskin",
        "specific_location": "Crumbling Farum Azula",
        "mandatory": True,
        "dlc": False,
        "runes": 160000,
        "image_url": "/static/images/Godskin_Duo.jpg"
    },
    "Crucible Knight Evergaol": {
        "name": "Crucible Knight Evergaol",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Stormhill Evergaol",
        "mandatory": False,
        "dlc": False,
        "runes": 3200,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Elden Ring's Black Knife Assassin": {
        "name": "Elden Ring's Black Knife Assassin",
        "region": "Limgrave",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Deathtouched Catacombs",
        "mandatory": False,
        "dlc": False,
        "runes": 1600,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Misbegotten Warrior": {
        "name": "Misbegotten Warrior",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Misbegotten",
        "specific_location": "Redmane Castle",
        "mandatory": False,
        "dlc": False,
        "runes": 14000,
        "image_url": "/static/images/Misbegotten_Warrior.jpg"
    },
    "Crucible Knight (Redmane)": {
        "name": "Crucible Knight (Redmane)",
        "region": "Caelid",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Redmane Castle",
        "mandatory": False,
        "dlc": False,
        "runes": 14000,
        "image_url": "/static/images/Crucible_Knight.jpg"
    },
    "Divine Beast Dancing Lion": {
        "name": "Divine Beast Dancing Lion",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Legend",
        "race": "Beast",
        "specific_location": "Belurat Tower Settlement",
        "mandatory": True,
        "dlc": True,
        "runes": 280000,
        "image_url": "/static/images/Divine_Beast_Dancing_Lion.jpg"
    },
    "Rellana, Twin Moon Knight": {
        "name": "Rellana, Twin Moon Knight",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Legend",
        "race": "Humanoid",
        "specific_location": "Castle Ensis",
        "mandatory": True,
        "dlc": True,
        "runes": 380000,
        "image_url": "/static/images/Rellana_Twin_Moon_Knight.jpg"
    },
    "Commander Gaius": {
        "name": "Commander Gaius",
        "region": "Scadu Altus",
        "phase": 1,
        "type": "Legend",
        "race": "Humanoid",
        "specific_location": "Shadow Keep",
        "mandatory": False,
        "dlc": True,
        "runes": 380000,
        "image_url": "/static/images/Commander_Gaius.jpg"
    },
    "Messmer the Impaler": {
        "name": "Messmer the Impaler",
        "region": "Scadu Altus",
        "phase": 2,
        "type": "Demigod",
        "race": "Humanoid",
        "specific_location": "Shadow Keep",
        "mandatory": True,
        "dlc": True,
        "runes": 420000,
        "image_url": "/static/images/Messmer_the_Impaler.jpg"
    },
    "Scadutree Avatar": {
        "name": "Scadutree Avatar",
        "region": "Scaduview",
        "phase": 3,
        "type": "Legend",
        "race": "Plant",
        "specific_location": "Scadutree Base",
        "mandatory": False,
        "dlc": True,
        "runes": 420000,
        "image_url": "/static/images/Scadutree_Avatar.jpg"
    },
    "Putrescent Knight": {
        "name": "Putrescent Knight",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Legend",
        "race": "Undead",
        "specific_location": "Stone Coffin Fissure",
        "mandatory": False,
        "dlc": True,
        "runes": 380000,
        "image_url": "/static/images/Putrescent_Knight.jpg"
    },
    "Romina, Saint of the Bud": {
        "name": "Romina, Saint of the Bud",
        "region": "Ancient Ruins of Rauh",
        "phase": 1,
        "type": "Legend",
        "race": "Bug",
        "specific_location": "Church of the Bud",
        "mandatory": True,
        "dlc": True,
        "runes": 420000,
        "image_url": "/static/images/Romina_Saint_of_the_Bud.jpg"
    },
    "Midra, Lord of Frenzied Flame": {
        "name": "Midra, Lord of Frenzied Flame",
        "region": "Abyssal Woods",
        "phase": 2,
        "type": "Legend",
        "race": "Humanoid",
        "specific_location": "Midra's Manse",
        "mandatory": False,
        "dlc": True,
        "runes": 380000,
        "image_url": "/static/images/Midra_Lord_of_Frenzied_Flame.jpg"
    },
    "Metyr, Mother of Fingers": {
        "name": "Metyr, Mother of Fingers",
        "region": "Scaduview",
        "phase": 2,
        "type": "Legend",
        "race": "Aberration",
        "specific_location": "Finger Ruins of Miyr",
        "mandatory": False,
        "dlc": True,
        "runes": 380000,
        "image_url": "/static/images/Metyr_Mother_of_Fingers.jpg"
    },
    "Bayle the Dread": {
        "name": "Bayle the Dread",
        "region": "Jagged Peak",
        "phase": 2,
        "type": "Legend",
        "race": "Dragon",
        "specific_location": "Jagged Peak",
        "mandatory": False,
        "dlc": True,
        "runes": 420000,
        "image_url": "/static/images/Bayle_the_Dread.jpg"
    },
    "Promised Consort Radahn": {
        "name": "Promised Consort Radahn",
        "region": "Shadow Realm",
        "phase": 2,
        "type": "Demigod",
        "race": "Humanoid",
        "specific_location": "Enir-Ilim",
        "mandatory": True,
        "dlc": True,
        "runes": 600000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Blackgaol Knight": {
        "name": "Blackgaol Knight",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Western Nameless Mausoleum",
        "mandatory": False,
        "dlc": True,
        "runes": 45000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Ghostflame Dragon": {
        "name": "Ghostflame Dragon",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Gravesite Plain",
        "mandatory": False,
        "dlc": True,
        "runes": 100000,
        "image_url": "/static/images/Ghostflame_Dragon.jpg"
    },
    "Demi-Human Queen Marigga": {
        "name": "Demi-Human Queen Marigga",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Demi-Human",
        "specific_location": "Gravesite Plain",
        "mandatory": False,
        "dlc": True,
        "runes": 20000,
        "image_url": "/static/images/Demi-Human_Queen_Marigga.jpg"
    },
    "Furnace Golem": {
        "name": "Furnace Golem",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Construct",
        "specific_location": "Gravesite Plain",
        "mandatory": False,
        "dlc": True,
        "runes": 90000,
        "image_url": "/static/images/Furnace_Golem.jpg"
    },
    "Golden Hippopotamus": {
        "name": "Golden Hippopotamus",
        "region": "Scadu Altus",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Beast",
        "specific_location": "Shadow Keep",
        "mandatory": True,
        "dlc": True,
        "runes": 280000,
        "image_url": "/static/images/Golden_Hippopotamus.jpg"
    },
    "Rakshasa": {
        "name": "Rakshasa",
        "region": "Scadu Altus",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Shadow Keep",
        "mandatory": False,
        "dlc": True,
        "runes": 200000,
        "image_url": "/static/images/Rakshasa.jpg"
    },
    "Black Knight Garrew": {
        "name": "Black Knight Garrew",
        "region": "Scadu Altus",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Fort of Reprimand",
        "mandatory": False,
        "dlc": True,
        "runes": 80000,
        "image_url": "/static/images/Black_Knight_Garrew.jpg"
    },
    "Rugalea the Great Red Bear": {
        "name": "Rugalea the Great Red Bear",
        "region": "Scadu Altus",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Beast",
        "specific_location": "Scadu Altus",
        "mandatory": False,
        "dlc": True,
        "runes": 100000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Death Knight": {
        "name": "Death Knight",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Undead",
        "specific_location": "Gravesite Plain",
        "mandatory": False,
        "dlc": True,
        "runes": 50000,
        "image_url": "/static/images/Death_Knight.jpg"
    },
    "Jori, Elder Inquisitor": {
        "name": "Jori, Elder Inquisitor",
        "region": "Abyssal Woods",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Midra's Manse",
        "mandatory": False,
        "dlc": True,
        "runes": 120000,
        "image_url": "/static/images/Jori_Elder_Inquisitor.jpg"
    },
    "Lamenter": {
        "name": "Lamenter",
        "region": "Abyssal Woods",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Abyssal Woods",
        "mandatory": False,
        "dlc": True,
        "runes": 80000,
        "image_url": "/static/images/Lamenter.jpg"
    },
    "Dancer of Ranah": {
        "name": "Dancer of Ranah",
        "region": "Ancient Ruins of Rauh",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Ancient Ruins of Rauh",
        "mandatory": False,
        "dlc": True,
        "runes": 150000,
        "image_url": "/static/images/Dancer_of_Ranah.jpg"
    },
    "Ralva the Great Red Bear": {
        "name": "Ralva the Great Red Bear",
        "region": "Ancient Ruins of Rauh",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Beast",
        "specific_location": "Ancient Ruins of Rauh",
        "mandatory": False,
        "dlc": True,
        "runes": 100000,
        "image_url": "/static/images/Ralva_the_Great_Red_Bear.jpg"
    },
    "Jagged Peak Drake": {
        "name": "Jagged Peak Drake",
        "region": "Jagged Peak",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Jagged Peak",
        "mandatory": False,
        "dlc": True,
        "runes": 60000,
        "image_url": "/static/images/Jagged_Peak_Drake.jpg"
    },
    "Ghostflame Dragon (Jagged Peak)": {
        "name": "Ghostflame Dragon (Jagged Peak)",
        "region": "Jagged Peak",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Jagged Peak",
        "mandatory": False,
        "dlc": True,
        "runes": 100000,
        "image_url": "/static/images/Ghostflame_Dragon.jpg"
    },
    "Demi-Human Swordmaster Onze": {
        "name": "Demi-Human Swordmaster Onze",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Demi-Human",
        "specific_location": "Gravesite Plain",
        "mandatory": False,
        "dlc": True,
        "runes": 30000,
        "image_url": "/static/images/Demi-Human_Swordmaster_Onze.jpg"
    },
    "Curseblade Labirith": {
        "name": "Curseblade Labirith",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Ruined Forge Lava Intake",
        "mandatory": False,
        "dlc": True,
        "runes": 30000,
        "image_url": "/static/images/Curseblade_Labirith.jpg"
    },
    "Tree Spirit of Fissure": {
        "name": "Tree Spirit of Fissure",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Tree Avatar",
        "specific_location": "Stone Coffin Fissure",
        "mandatory": False,
        "dlc": True,
        "runes": 80000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Messmer Soldier (Evergaol)": {
        "name": "Messmer Soldier (Evergaol)",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Fog Rift Catacombs",
        "mandatory": False,
        "dlc": True,
        "runes": 25000,
        "image_url": "/static/images/Messmer_Soldier_Evergaol.jpg"
    },
    "Sunflower": {
        "name": "Sunflower",
        "region": "Scadu Altus",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Plant",
        "specific_location": "Scadu Altus",
        "mandatory": False,
        "dlc": True,
        "runes": 50000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Ancient Dragon Senessax": {
        "name": "Ancient Dragon Senessax",
        "region": "Ancient Ruins of Rauh",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Dragon",
        "specific_location": "Ancient Ruins of Rauh",
        "mandatory": False,
        "dlc": True,
        "runes": 120000,
        "image_url": "/static/images/Ancient_Dragon_Senessax.jpg"
    },
    "Bloodfiend Crucible": {
        "name": "Bloodfiend Crucible",
        "region": "Ancient Ruins of Rauh",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Humanoid",
        "specific_location": "Ancient Ruins of Rauh",
        "mandatory": False,
        "dlc": True,
        "runes": 60000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Romina's Phantom": {
        "name": "Romina's Phantom",
        "region": "Ancient Ruins of Rauh",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Bug",
        "specific_location": "Church of the Bud",
        "mandatory": False,
        "dlc": True,
        "runes": 50000,
        "image_url": "/static/images/Demi-Human_Chiefs.jpg"
    },
    "Gravebird": {
        "name": "Gravebird",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Bird",
        "specific_location": "Belurat Gaol",
        "mandatory": False,
        "dlc": True,
        "runes": 20000,
        "image_url": "/static/images/Gravebird.jpg"
    },
    "Ulcerated Tree Spirit (DLC)": {
        "name": "Ulcerated Tree Spirit (DLC)",
        "region": "Gravesite Plain",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Tree Avatar",
        "specific_location": "Gravesite Plain",
        "mandatory": False,
        "dlc": True,
        "runes": 50000,
        "image_url": "/static/images/Ulcerated_Tree_Spirit_Gelmir.jpg"
    },
    "Fingercreeper (Shadow Keep)": {
        "name": "Fingercreeper (Shadow Keep)",
        "region": "Scadu Altus",
        "phase": 1,
        "type": "Greater Enemy",
        "race": "Aberration",
        "specific_location": "Shadow Keep",
        "mandatory": False,
        "dlc": True,
        "runes": 40000,
        "image_url": "/static/images/Fingercreeper_Shadow_Keep.jpg"
    },
}
